version: '2.4'
x-database-variables: &database-variable
  SPRING_DATASOURCE_URL: jdbc:mysql://MYSQL:3306/hospital-query-system?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dracarys_data:/var/lib/mysql
    mem_limit: 512m

volumes:
  dracarys_data: