server:
  error:
    include-stacktrace: on_param
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital-system
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: off

application:
  security:
    jwt:
      secret-key: '2a502fb2-5596-11ed-bdc3-0242ac120002'
      expiration: '600000'