server:
  error:
    include-stacktrace: on_param
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: off